runs-on: ubuntu-latest

name: Build
on: [push]

jobs:
  build:
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Read .nvmrc
        id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build --if-present