name: Publish
on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          known_hosts: unnecessary

      -name: Adding know host
        run: ssh-keyscan -p ${{ secrets.DEPLOY_SERVER_KEY }} -H ${{ secrets.DEPLOY_SERVER_HOST }} >> ~/.ssh/known_host

#      -name: Run Docker
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.DEPLOY_SERVER_HOST }}
#          port: ${{ secrets.DEPLOY_SERVER_PORT }}
#          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
#          key: ${{ secrets.DEPLOY_SERVER_KEY }}
#          command_timeout: 35m
#          script: |
#            cd prod
#            pwd
#            ls -la
#            sudo docker-compose up -d --build